//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class CropCyclesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * List field crop cycles
     * @return OK
     */
    cropCyclesGET(fieldId: string): Promise<CropCycleCollectionDto> {
        let url_ = this.baseUrl + "/api/fields/{fieldId}/crop-cycles";
        if (fieldId === undefined || fieldId === null)
            throw new globalThis.Error("The parameter 'fieldId' must be defined.");
        url_ = url_.replace("{fieldId}", encodeURIComponent("" + fieldId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCropCyclesGET(_response);
        });
    }

    protected processCropCyclesGET(response: Response): Promise<CropCycleCollectionDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CropCycleCollectionDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropCycleCollectionDto>(null as any);
    }

    /**
     * Create crop-cycle draft
     * @return Created
     */
    cropCyclesPOST(fieldId: string, body: CreateCropCycleRequest): Promise<CropCycleDetailsDto> {
        let url_ = this.baseUrl + "/api/fields/{fieldId}/crop-cycles";
        if (fieldId === undefined || fieldId === null)
            throw new globalThis.Error("The parameter 'fieldId' must be defined.");
        url_ = url_.replace("{fieldId}", encodeURIComponent("" + fieldId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCropCyclesPOST(_response);
        });
    }

    protected processCropCyclesPOST(response: Response): Promise<CropCycleDetailsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CropCycleDetailsDto.fromJS(resultData201);
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropCycleDetailsDto>(null as any);
    }

    /**
     * Get crop-cycle overview
     * @return OK
     */
    cropCyclesGET2(fieldId: string, cropCycleId: string): Promise<CropCycleDetailsDto> {
        let url_ = this.baseUrl + "/api/fields/{fieldId}/crop-cycles/{cropCycleId}";
        if (fieldId === undefined || fieldId === null)
            throw new globalThis.Error("The parameter 'fieldId' must be defined.");
        url_ = url_.replace("{fieldId}", encodeURIComponent("" + fieldId));
        if (cropCycleId === undefined || cropCycleId === null)
            throw new globalThis.Error("The parameter 'cropCycleId' must be defined.");
        url_ = url_.replace("{cropCycleId}", encodeURIComponent("" + cropCycleId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCropCyclesGET2(_response);
        });
    }

    protected processCropCyclesGET2(response: Response): Promise<CropCycleDetailsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CropCycleDetailsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropCycleDetailsDto>(null as any);
    }

    /**
     * @return OK
     */
    activate(fieldId: string, cropCycleId: string, body: TransitionCropCycleRequest): Promise<CropCycleDetailsDto> {
        let url_ = this.baseUrl + "/api/fields/{fieldId}/crop-cycles/{cropCycleId}/transitions/activate";
        if (fieldId === undefined || fieldId === null)
            throw new globalThis.Error("The parameter 'fieldId' must be defined.");
        url_ = url_.replace("{fieldId}", encodeURIComponent("" + fieldId));
        if (cropCycleId === undefined || cropCycleId === null)
            throw new globalThis.Error("The parameter 'cropCycleId' must be defined.");
        url_ = url_.replace("{cropCycleId}", encodeURIComponent("" + cropCycleId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processActivate(_response);
        });
    }

    protected processActivate(response: Response): Promise<CropCycleDetailsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CropCycleDetailsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropCycleDetailsDto>(null as any);
    }

    /**
     * @return OK
     */
    cancel(fieldId: string, cropCycleId: string, body: CancelCropCycleRequest): Promise<CropCycleDetailsDto> {
        let url_ = this.baseUrl + "/api/fields/{fieldId}/crop-cycles/{cropCycleId}/transitions/cancel";
        if (fieldId === undefined || fieldId === null)
            throw new globalThis.Error("The parameter 'fieldId' must be defined.");
        url_ = url_.replace("{fieldId}", encodeURIComponent("" + fieldId));
        if (cropCycleId === undefined || cropCycleId === null)
            throw new globalThis.Error("The parameter 'cropCycleId' must be defined.");
        url_ = url_.replace("{cropCycleId}", encodeURIComponent("" + cropCycleId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCancel(_response);
        });
    }

    protected processCancel(response: Response): Promise<CropCycleDetailsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CropCycleDetailsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropCycleDetailsDto>(null as any);
    }

    /**
     * @return OK
     */
    readyForHarvest(fieldId: string, cropCycleId: string, body: TransitionCropCycleRequest): Promise<CropCycleDetailsDto> {
        let url_ = this.baseUrl + "/api/fields/{fieldId}/crop-cycles/{cropCycleId}/transitions/ready-for-harvest";
        if (fieldId === undefined || fieldId === null)
            throw new globalThis.Error("The parameter 'fieldId' must be defined.");
        url_ = url_.replace("{fieldId}", encodeURIComponent("" + fieldId));
        if (cropCycleId === undefined || cropCycleId === null)
            throw new globalThis.Error("The parameter 'cropCycleId' must be defined.");
        url_ = url_.replace("{cropCycleId}", encodeURIComponent("" + cropCycleId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processReadyForHarvest(_response);
        });
    }

    protected processReadyForHarvest(response: Response): Promise<CropCycleDetailsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CropCycleDetailsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropCycleDetailsDto>(null as any);
    }

    /**
     * @return OK
     */
    harvest(fieldId: string, cropCycleId: string, body: HarvestCropCycleRequest): Promise<CropCycleDetailsDto> {
        let url_ = this.baseUrl + "/api/fields/{fieldId}/crop-cycles/{cropCycleId}/transitions/harvest";
        if (fieldId === undefined || fieldId === null)
            throw new globalThis.Error("The parameter 'fieldId' must be defined.");
        url_ = url_.replace("{fieldId}", encodeURIComponent("" + fieldId));
        if (cropCycleId === undefined || cropCycleId === null)
            throw new globalThis.Error("The parameter 'cropCycleId' must be defined.");
        url_ = url_.replace("{cropCycleId}", encodeURIComponent("" + cropCycleId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHarvest(_response);
        });
    }

    protected processHarvest(response: Response): Promise<CropCycleDetailsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CropCycleDetailsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropCycleDetailsDto>(null as any);
    }

    /**
     * @return OK
     */
    close(fieldId: string, cropCycleId: string, body: TransitionCropCycleRequest): Promise<CropCycleDetailsDto> {
        let url_ = this.baseUrl + "/api/fields/{fieldId}/crop-cycles/{cropCycleId}/transitions/close";
        if (fieldId === undefined || fieldId === null)
            throw new globalThis.Error("The parameter 'fieldId' must be defined.");
        url_ = url_.replace("{fieldId}", encodeURIComponent("" + fieldId));
        if (cropCycleId === undefined || cropCycleId === null)
            throw new globalThis.Error("The parameter 'cropCycleId' must be defined.");
        url_ = url_.replace("{cropCycleId}", encodeURIComponent("" + cropCycleId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processClose(_response);
        });
    }

    protected processClose(response: Response): Promise<CropCycleDetailsDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CropCycleDetailsDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropCycleDetailsDto>(null as any);
    }
}

export class CropVarietiesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    cropVarietiesAll(): Promise<CropVarietyDto[]> {
        let url_ = this.baseUrl + "/api/CropVarieties";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCropVarietiesAll(_response);
        });
    }

    protected processCropVarietiesAll(response: Response): Promise<CropVarietyDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(CropVarietyDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropVarietyDto[]>(null as any);
    }

    /**
     * @return Created
     */
    cropVarieties(body: CreateCropVarietyRequest): Promise<CropVarietyDto> {
        let url_ = this.baseUrl + "/api/CropVarieties";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCropVarieties(_response);
        });
    }

    protected processCropVarieties(response: Response): Promise<CropVarietyDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 201) {
            return response.text().then((_responseText) => {
            let result201: any = null;
            let resultData201 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result201 = CropVarietyDto.fromJS(resultData201);
            return result201;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            return throwException("Unauthorized", status, _responseText, _headers);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CropVarietyDto>(null as any);
    }
}

export class FarmSetupClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Get farm setup
     * @return OK
     */
    farmSetup(): Promise<FarmSetupDto> {
        let url_ = this.baseUrl + "/api/FarmSetup";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFarmSetup(_response);
        });
    }

    protected processFarmSetup(response: Response): Promise<FarmSetupDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FarmSetupDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FarmSetupDto>(null as any);
    }

    /**
     * Create grower farm
     * @return OK
     */
    farm(body: CreateGrowerFarmRequest): Promise<FarmSetupDto> {
        let url_ = this.baseUrl + "/api/FarmSetup/farm";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFarm(_response);
        });
    }

    protected processFarm(response: Response): Promise<FarmSetupDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FarmSetupDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FarmSetupDto>(null as any);
    }

    /**
     * Create field
     * @return OK
     */
    fields(body: CreateFieldRequest): Promise<FarmSetupDto> {
        let url_ = this.baseUrl + "/api/FarmSetup/fields";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processFields(_response);
        });
    }

    protected processFields(response: Response): Promise<FarmSetupDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = FarmSetupDto.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FarmSetupDto>(null as any);
    }
}

export class HealthClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Health check
     * @return OK
     */
    health(): Promise<void> {
        let url_ = this.baseUrl + "/api/Health";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHealth(_response);
        });
    }

    protected processHealth(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 503) {
            return response.text().then((_responseText) => {
            return throwException("Service Unavailable", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class UsersClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * Register
     * @return OK
     */
    register(body: RegisterRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/Users/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ValidationProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Log in
     * @param useCookies (optional)
     * @param useSessionCookies (optional)
     * @return OK
     */
    login(useCookies: boolean | undefined, useSessionCookies: boolean | undefined, body: LoginRequest): Promise<void> {
        let url_ = this.baseUrl + "/api/Users/login?";
        if (useCookies === null)
            throw new globalThis.Error("The parameter 'useCookies' cannot be null.");
        else if (useCookies !== undefined)
            url_ += "useCookies=" + encodeURIComponent("" + useCookies) + "&";
        if (useSessionCookies === null)
            throw new globalThis.Error("The parameter 'useSessionCookies' cannot be null.");
        else if (useSessionCookies !== undefined)
            url_ += "useSessionCookies=" + encodeURIComponent("" + useSessionCookies) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Log out
     * @return OK
     */
    logout(): Promise<void> {
        let url_ = this.baseUrl + "/api/Users/logout";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processLogout(_response);
        });
    }

    protected processLogout(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Get account info
     * @return OK
     */
    info(): Promise<UserInfoResponse> {
        let url_ = this.baseUrl + "/api/Users/manage/info";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processInfo(_response);
        });
    }

    protected processInfo(response: Response): Promise<UserInfoResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserInfoResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            return throwException("Bad Request", status, _responseText, _headers);
            });
        } else if (status === 401) {
            return response.text().then((_responseText) => {
            let result401: any = null;
            let resultData401 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);
            });
        } else if (status === 403) {
            return response.text().then((_responseText) => {
            return throwException("Forbidden", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserInfoResponse>(null as any);
    }
}

export class CancelCropCycleRequest implements ICancelCropCycleRequest {
    expectedVersion!: number;
    reason!: string;

    [key: string]: any;

    constructor(data?: ICancelCropCycleRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.expectedVersion = _data["expectedVersion"];
            this.reason = _data["reason"];
        }
    }

    static fromJS(data: any): CancelCropCycleRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CancelCropCycleRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["expectedVersion"] = this.expectedVersion;
        data["reason"] = this.reason;
        return data;
    }
}

export interface ICancelCropCycleRequest {
    expectedVersion: number;
    reason: string;

    [key: string]: any;
}

export class CreateCropCycleRequest implements ICreateCropCycleRequest {
    cycleType!: string;
    ratoonNumber!: number | undefined;
    cropVarietyId!: string;
    startDate!: Date;
    expectedHarvestStart!: Date;
    expectedHarvestEnd!: Date;
    expectedYieldTonnes!: number;

    [key: string]: any;

    constructor(data?: ICreateCropCycleRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.cycleType = _data["cycleType"];
            this.ratoonNumber = _data["ratoonNumber"];
            this.cropVarietyId = _data["cropVarietyId"];
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : undefined as any;
            this.expectedHarvestStart = _data["expectedHarvestStart"] ? new Date(_data["expectedHarvestStart"].toString()) : undefined as any;
            this.expectedHarvestEnd = _data["expectedHarvestEnd"] ? new Date(_data["expectedHarvestEnd"].toString()) : undefined as any;
            this.expectedYieldTonnes = _data["expectedYieldTonnes"];
        }
    }

    static fromJS(data: any): CreateCropCycleRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateCropCycleRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["cycleType"] = this.cycleType;
        data["ratoonNumber"] = this.ratoonNumber;
        data["cropVarietyId"] = this.cropVarietyId;
        data["startDate"] = this.startDate ? formatDate(this.startDate) : undefined as any;
        data["expectedHarvestStart"] = this.expectedHarvestStart ? formatDate(this.expectedHarvestStart) : undefined as any;
        data["expectedHarvestEnd"] = this.expectedHarvestEnd ? formatDate(this.expectedHarvestEnd) : undefined as any;
        data["expectedYieldTonnes"] = this.expectedYieldTonnes;
        return data;
    }
}

export interface ICreateCropCycleRequest {
    cycleType: string;
    ratoonNumber: number | undefined;
    cropVarietyId: string;
    startDate: Date;
    expectedHarvestStart: Date;
    expectedHarvestEnd: Date;
    expectedYieldTonnes: number;

    [key: string]: any;
}

export class CreateCropVarietyRequest implements ICreateCropVarietyRequest {
    code!: string;
    name!: string;

    [key: string]: any;

    constructor(data?: ICreateCropVarietyRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.code = _data["code"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CreateCropVarietyRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateCropVarietyRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["code"] = this.code;
        data["name"] = this.name;
        return data;
    }
}

export interface ICreateCropVarietyRequest {
    code: string;
    name: string;

    [key: string]: any;
}

export class CreateFieldRequest implements ICreateFieldRequest {
    code!: string;
    name!: string;
    declaredHectares!: number;
    mappedHectares!: number | undefined;
    reportingAreaSource!: string;
    irrigationMethod!: string;
    soilNotes!: string | undefined;

    [key: string]: any;

    constructor(data?: ICreateFieldRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.code = _data["code"];
            this.name = _data["name"];
            this.declaredHectares = _data["declaredHectares"];
            this.mappedHectares = _data["mappedHectares"];
            this.reportingAreaSource = _data["reportingAreaSource"];
            this.irrigationMethod = _data["irrigationMethod"];
            this.soilNotes = _data["soilNotes"];
        }
    }

    static fromJS(data: any): CreateFieldRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateFieldRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["code"] = this.code;
        data["name"] = this.name;
        data["declaredHectares"] = this.declaredHectares;
        data["mappedHectares"] = this.mappedHectares;
        data["reportingAreaSource"] = this.reportingAreaSource;
        data["irrigationMethod"] = this.irrigationMethod;
        data["soilNotes"] = this.soilNotes;
        return data;
    }
}

export interface ICreateFieldRequest {
    code: string;
    name: string;
    declaredHectares: number;
    mappedHectares: number | undefined;
    reportingAreaSource: string;
    irrigationMethod: string;
    soilNotes: string | undefined;

    [key: string]: any;
}

export class CreateGrowerFarmRequest implements ICreateGrowerFarmRequest {
    growerDisplayName!: string;
    growerPhone!: string | undefined;
    farmCode!: string;
    farmName!: string;
    address!: string;
    location!: string;
    tenure!: string;
    declaredHectares!: number;
    irrigationContext!: string;

    [key: string]: any;

    constructor(data?: ICreateGrowerFarmRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.growerDisplayName = _data["growerDisplayName"];
            this.growerPhone = _data["growerPhone"];
            this.farmCode = _data["farmCode"];
            this.farmName = _data["farmName"];
            this.address = _data["address"];
            this.location = _data["location"];
            this.tenure = _data["tenure"];
            this.declaredHectares = _data["declaredHectares"];
            this.irrigationContext = _data["irrigationContext"];
        }
    }

    static fromJS(data: any): CreateGrowerFarmRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateGrowerFarmRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["growerDisplayName"] = this.growerDisplayName;
        data["growerPhone"] = this.growerPhone;
        data["farmCode"] = this.farmCode;
        data["farmName"] = this.farmName;
        data["address"] = this.address;
        data["location"] = this.location;
        data["tenure"] = this.tenure;
        data["declaredHectares"] = this.declaredHectares;
        data["irrigationContext"] = this.irrigationContext;
        return data;
    }
}

export interface ICreateGrowerFarmRequest {
    growerDisplayName: string;
    growerPhone: string | undefined;
    farmCode: string;
    farmName: string;
    address: string;
    location: string;
    tenure: string;
    declaredHectares: number;
    irrigationContext: string;

    [key: string]: any;
}

export class CropCycleCollectionDto implements ICropCycleCollectionDto {
    field!: CropCycleFieldDto;
    cropCycles!: CropCycleListItemDto[];

    [key: string]: any;

    constructor(data?: ICropCycleCollectionDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.field = new CropCycleFieldDto();
            this.cropCycles = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.field = _data["field"] ? CropCycleFieldDto.fromJS(_data["field"]) : new CropCycleFieldDto();
            if (Array.isArray(_data["cropCycles"])) {
                this.cropCycles = [] as any;
                for (let item of _data["cropCycles"])
                    this.cropCycles!.push(CropCycleListItemDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CropCycleCollectionDto {
        data = typeof data === 'object' ? data : {};
        let result = new CropCycleCollectionDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["field"] = this.field ? this.field.toJSON() : undefined as any;
        if (Array.isArray(this.cropCycles)) {
            data["cropCycles"] = [];
            for (let item of this.cropCycles)
                data["cropCycles"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ICropCycleCollectionDto {
    field: CropCycleFieldDto;
    cropCycles: CropCycleListItemDto[];

    [key: string]: any;
}

export class CropCycleDetailsDto implements ICropCycleDetailsDto {
    field!: CropCycleFieldDto;
    cropCycle!: CropCycleListItemDto;
    allowedTransitions!: string[];
    blockedTransitions!: { [key: string]: string; };
    timeline!: CropCycleTimelineEventDto[];

    [key: string]: any;

    constructor(data?: ICropCycleDetailsDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.field = new CropCycleFieldDto();
            this.cropCycle = new CropCycleListItemDto();
            this.allowedTransitions = [];
            this.blockedTransitions = {};
            this.timeline = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.field = _data["field"] ? CropCycleFieldDto.fromJS(_data["field"]) : new CropCycleFieldDto();
            this.cropCycle = _data["cropCycle"] ? CropCycleListItemDto.fromJS(_data["cropCycle"]) : new CropCycleListItemDto();
            if (Array.isArray(_data["allowedTransitions"])) {
                this.allowedTransitions = [] as any;
                for (let item of _data["allowedTransitions"])
                    this.allowedTransitions!.push(item);
            }
            if (_data["blockedTransitions"]) {
                this.blockedTransitions = {} as any;
                for (let key in _data["blockedTransitions"]) {
                    if (_data["blockedTransitions"].hasOwnProperty(key))
                        (this.blockedTransitions as any)![key] = _data["blockedTransitions"][key];
                }
            }
            if (Array.isArray(_data["timeline"])) {
                this.timeline = [] as any;
                for (let item of _data["timeline"])
                    this.timeline!.push(CropCycleTimelineEventDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CropCycleDetailsDto {
        data = typeof data === 'object' ? data : {};
        let result = new CropCycleDetailsDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["field"] = this.field ? this.field.toJSON() : undefined as any;
        data["cropCycle"] = this.cropCycle ? this.cropCycle.toJSON() : undefined as any;
        if (Array.isArray(this.allowedTransitions)) {
            data["allowedTransitions"] = [];
            for (let item of this.allowedTransitions)
                data["allowedTransitions"].push(item);
        }
        if (this.blockedTransitions) {
            data["blockedTransitions"] = {};
            for (let key in this.blockedTransitions) {
                if (this.blockedTransitions.hasOwnProperty(key))
                    (data["blockedTransitions"] as any)[key] = (this.blockedTransitions as any)[key];
            }
        }
        if (Array.isArray(this.timeline)) {
            data["timeline"] = [];
            for (let item of this.timeline)
                data["timeline"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ICropCycleDetailsDto {
    field: CropCycleFieldDto;
    cropCycle: CropCycleListItemDto;
    allowedTransitions: string[];
    blockedTransitions: { [key: string]: string; };
    timeline: CropCycleTimelineEventDto[];

    [key: string]: any;
}

export class CropCycleDto implements ICropCycleDto {
    id!: string;
    cycleType!: string;
    ratoonNumber!: number | undefined;
    variety!: string;
    startDate!: string;
    expectedHarvestStart!: string;
    expectedHarvestEnd!: string;
    expectedYieldTonnes!: number;
    status!: string;

    [key: string]: any;

    constructor(data?: ICropCycleDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.cycleType = _data["cycleType"];
            this.ratoonNumber = _data["ratoonNumber"];
            this.variety = _data["variety"];
            this.startDate = _data["startDate"];
            this.expectedHarvestStart = _data["expectedHarvestStart"];
            this.expectedHarvestEnd = _data["expectedHarvestEnd"];
            this.expectedYieldTonnes = _data["expectedYieldTonnes"];
            this.status = _data["status"];
        }
    }

    static fromJS(data: any): CropCycleDto {
        data = typeof data === 'object' ? data : {};
        let result = new CropCycleDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["cycleType"] = this.cycleType;
        data["ratoonNumber"] = this.ratoonNumber;
        data["variety"] = this.variety;
        data["startDate"] = this.startDate;
        data["expectedHarvestStart"] = this.expectedHarvestStart;
        data["expectedHarvestEnd"] = this.expectedHarvestEnd;
        data["expectedYieldTonnes"] = this.expectedYieldTonnes;
        data["status"] = this.status;
        return data;
    }
}

export interface ICropCycleDto {
    id: string;
    cycleType: string;
    ratoonNumber: number | undefined;
    variety: string;
    startDate: string;
    expectedHarvestStart: string;
    expectedHarvestEnd: string;
    expectedYieldTonnes: number;
    status: string;

    [key: string]: any;
}

export class CropCycleFieldDto implements ICropCycleFieldDto {
    id!: string;
    code!: string;
    name!: string;
    reportingHectares!: number;

    [key: string]: any;

    constructor(data?: ICropCycleFieldDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.reportingHectares = _data["reportingHectares"];
        }
    }

    static fromJS(data: any): CropCycleFieldDto {
        data = typeof data === 'object' ? data : {};
        let result = new CropCycleFieldDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        data["reportingHectares"] = this.reportingHectares;
        return data;
    }
}

export interface ICropCycleFieldDto {
    id: string;
    code: string;
    name: string;
    reportingHectares: number;

    [key: string]: any;
}

export class CropCycleListItemDto implements ICropCycleListItemDto {
    id!: string;
    cycleType!: string;
    ratoonNumber!: number | undefined;
    cropVarietyId!: string | undefined;
    variety!: string;
    startDate!: string;
    expectedHarvestStart!: string;
    expectedHarvestEnd!: string;
    expectedYieldTonnes!: number;
    status!: string;
    version!: number;
    harvestResult!: HarvestResultDto | undefined;

    [key: string]: any;

    constructor(data?: ICropCycleListItemDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.cycleType = _data["cycleType"];
            this.ratoonNumber = _data["ratoonNumber"];
            this.cropVarietyId = _data["cropVarietyId"];
            this.variety = _data["variety"];
            this.startDate = _data["startDate"];
            this.expectedHarvestStart = _data["expectedHarvestStart"];
            this.expectedHarvestEnd = _data["expectedHarvestEnd"];
            this.expectedYieldTonnes = _data["expectedYieldTonnes"];
            this.status = _data["status"];
            this.version = _data["version"];
            this.harvestResult = _data["harvestResult"] ? HarvestResultDto.fromJS(_data["harvestResult"]) : undefined as any;
        }
    }

    static fromJS(data: any): CropCycleListItemDto {
        data = typeof data === 'object' ? data : {};
        let result = new CropCycleListItemDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["cycleType"] = this.cycleType;
        data["ratoonNumber"] = this.ratoonNumber;
        data["cropVarietyId"] = this.cropVarietyId;
        data["variety"] = this.variety;
        data["startDate"] = this.startDate;
        data["expectedHarvestStart"] = this.expectedHarvestStart;
        data["expectedHarvestEnd"] = this.expectedHarvestEnd;
        data["expectedYieldTonnes"] = this.expectedYieldTonnes;
        data["status"] = this.status;
        data["version"] = this.version;
        data["harvestResult"] = this.harvestResult ? this.harvestResult.toJSON() : undefined as any;
        return data;
    }
}

export interface ICropCycleListItemDto {
    id: string;
    cycleType: string;
    ratoonNumber: number | undefined;
    cropVarietyId: string | undefined;
    variety: string;
    startDate: string;
    expectedHarvestStart: string;
    expectedHarvestEnd: string;
    expectedYieldTonnes: number;
    status: string;
    version: number;
    harvestResult: HarvestResultDto | undefined;

    [key: string]: any;
}

export class CropCycleTimelineEventDto implements ICropCycleTimelineEventDto {
    id!: string;
    type!: string;
    title!: string;
    eventDate!: string;
    recordedAt!: string;
    detail!: string | undefined;
    reason!: string | undefined;

    [key: string]: any;

    constructor(data?: ICropCycleTimelineEventDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.type = _data["type"];
            this.title = _data["title"];
            this.eventDate = _data["eventDate"];
            this.recordedAt = _data["recordedAt"];
            this.detail = _data["detail"];
            this.reason = _data["reason"];
        }
    }

    static fromJS(data: any): CropCycleTimelineEventDto {
        data = typeof data === 'object' ? data : {};
        let result = new CropCycleTimelineEventDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["type"] = this.type;
        data["title"] = this.title;
        data["eventDate"] = this.eventDate;
        data["recordedAt"] = this.recordedAt;
        data["detail"] = this.detail;
        data["reason"] = this.reason;
        return data;
    }
}

export interface ICropCycleTimelineEventDto {
    id: string;
    type: string;
    title: string;
    eventDate: string;
    recordedAt: string;
    detail: string | undefined;
    reason: string | undefined;

    [key: string]: any;
}

export class CropVarietyDto implements ICropVarietyDto {
    id!: string;
    code!: string;
    name!: string;

    [key: string]: any;

    constructor(data?: ICropVarietyDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
        }
    }

    static fromJS(data: any): CropVarietyDto {
        data = typeof data === 'object' ? data : {};
        let result = new CropVarietyDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        return data;
    }
}

export interface ICropVarietyDto {
    id: string;
    code: string;
    name: string;

    [key: string]: any;
}

export class FarmDto implements IFarmDto {
    id!: string;
    code!: string;
    name!: string;
    address!: string;
    location!: string;
    tenure!: string;
    declaredHectares!: number;
    irrigationContext!: string;
    fields!: FieldDto[];

    [key: string]: any;

    constructor(data?: IFarmDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.fields = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.address = _data["address"];
            this.location = _data["location"];
            this.tenure = _data["tenure"];
            this.declaredHectares = _data["declaredHectares"];
            this.irrigationContext = _data["irrigationContext"];
            if (Array.isArray(_data["fields"])) {
                this.fields = [] as any;
                for (let item of _data["fields"])
                    this.fields!.push(FieldDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): FarmDto {
        data = typeof data === 'object' ? data : {};
        let result = new FarmDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        data["address"] = this.address;
        data["location"] = this.location;
        data["tenure"] = this.tenure;
        data["declaredHectares"] = this.declaredHectares;
        data["irrigationContext"] = this.irrigationContext;
        if (Array.isArray(this.fields)) {
            data["fields"] = [];
            for (let item of this.fields)
                data["fields"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IFarmDto {
    id: string;
    code: string;
    name: string;
    address: string;
    location: string;
    tenure: string;
    declaredHectares: number;
    irrigationContext: string;
    fields: FieldDto[];

    [key: string]: any;
}

export class FarmSetupDto implements IFarmSetupDto {
    isConfigured!: boolean;
    grower!: GrowerDto | undefined;
    farm!: FarmDto | undefined;

    [key: string]: any;

    constructor(data?: IFarmSetupDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.isConfigured = _data["isConfigured"];
            this.grower = _data["grower"] ? GrowerDto.fromJS(_data["grower"]) : undefined as any;
            this.farm = _data["farm"] ? FarmDto.fromJS(_data["farm"]) : undefined as any;
        }
    }

    static fromJS(data: any): FarmSetupDto {
        data = typeof data === 'object' ? data : {};
        let result = new FarmSetupDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["isConfigured"] = this.isConfigured;
        data["grower"] = this.grower ? this.grower.toJSON() : undefined as any;
        data["farm"] = this.farm ? this.farm.toJSON() : undefined as any;
        return data;
    }
}

export interface IFarmSetupDto {
    isConfigured: boolean;
    grower: GrowerDto | undefined;
    farm: FarmDto | undefined;

    [key: string]: any;
}

export class FieldDto implements IFieldDto {
    id!: string;
    code!: string;
    name!: string;
    declaredHectares!: number;
    mappedHectares!: number | undefined;
    reportingHectares!: number;
    reportingAreaSource!: string;
    irrigationMethod!: string;
    soilNotes!: string | undefined;
    currentCropCycle!: CropCycleDto | undefined;

    [key: string]: any;

    constructor(data?: IFieldDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.declaredHectares = _data["declaredHectares"];
            this.mappedHectares = _data["mappedHectares"];
            this.reportingHectares = _data["reportingHectares"];
            this.reportingAreaSource = _data["reportingAreaSource"];
            this.irrigationMethod = _data["irrigationMethod"];
            this.soilNotes = _data["soilNotes"];
            this.currentCropCycle = _data["currentCropCycle"] ? CropCycleDto.fromJS(_data["currentCropCycle"]) : undefined as any;
        }
    }

    static fromJS(data: any): FieldDto {
        data = typeof data === 'object' ? data : {};
        let result = new FieldDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        data["declaredHectares"] = this.declaredHectares;
        data["mappedHectares"] = this.mappedHectares;
        data["reportingHectares"] = this.reportingHectares;
        data["reportingAreaSource"] = this.reportingAreaSource;
        data["irrigationMethod"] = this.irrigationMethod;
        data["soilNotes"] = this.soilNotes;
        data["currentCropCycle"] = this.currentCropCycle ? this.currentCropCycle.toJSON() : undefined as any;
        return data;
    }
}

export interface IFieldDto {
    id: string;
    code: string;
    name: string;
    declaredHectares: number;
    mappedHectares: number | undefined;
    reportingHectares: number;
    reportingAreaSource: string;
    irrigationMethod: string;
    soilNotes: string | undefined;
    currentCropCycle: CropCycleDto | undefined;

    [key: string]: any;
}

export class GrowerDto implements IGrowerDto {
    displayName!: string;
    phone!: string | undefined;

    [key: string]: any;

    constructor(data?: IGrowerDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.displayName = _data["displayName"];
            this.phone = _data["phone"];
        }
    }

    static fromJS(data: any): GrowerDto {
        data = typeof data === 'object' ? data : {};
        let result = new GrowerDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["displayName"] = this.displayName;
        data["phone"] = this.phone;
        return data;
    }
}

export interface IGrowerDto {
    displayName: string;
    phone: string | undefined;

    [key: string]: any;
}

export class HarvestCropCycleRequest implements IHarvestCropCycleRequest {
    expectedVersion!: number;
    harvestDate!: Date;
    actualTonnes!: number;

    [key: string]: any;

    constructor(data?: IHarvestCropCycleRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.expectedVersion = _data["expectedVersion"];
            this.harvestDate = _data["harvestDate"] ? new Date(_data["harvestDate"].toString()) : undefined as any;
            this.actualTonnes = _data["actualTonnes"];
        }
    }

    static fromJS(data: any): HarvestCropCycleRequest {
        data = typeof data === 'object' ? data : {};
        let result = new HarvestCropCycleRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["expectedVersion"] = this.expectedVersion;
        data["harvestDate"] = this.harvestDate ? formatDate(this.harvestDate) : undefined as any;
        data["actualTonnes"] = this.actualTonnes;
        return data;
    }
}

export interface IHarvestCropCycleRequest {
    expectedVersion: number;
    harvestDate: Date;
    actualTonnes: number;

    [key: string]: any;
}

export class HarvestResultDto implements IHarvestResultDto {
    harvestDate!: string;
    actualTonnes!: number;

    [key: string]: any;

    constructor(data?: IHarvestResultDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.harvestDate = _data["harvestDate"];
            this.actualTonnes = _data["actualTonnes"];
        }
    }

    static fromJS(data: any): HarvestResultDto {
        data = typeof data === 'object' ? data : {};
        let result = new HarvestResultDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["harvestDate"] = this.harvestDate;
        data["actualTonnes"] = this.actualTonnes;
        return data;
    }
}

export interface IHarvestResultDto {
    harvestDate: string;
    actualTonnes: number;

    [key: string]: any;
}

export class LoginRequest implements ILoginRequest {
    email!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginRequest {
    email: string;
    password: string;

    [key: string]: any;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export class RegisterRequest implements IRegisterRequest {
    email!: string;
    password!: string;

    [key: string]: any;

    constructor(data?: IRegisterRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): RegisterRequest {
        data = typeof data === 'object' ? data : {};
        let result = new RegisterRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["password"] = this.password;
        return data;
    }
}

export interface IRegisterRequest {
    email: string;
    password: string;

    [key: string]: any;
}

export class TransitionCropCycleRequest implements ITransitionCropCycleRequest {
    expectedVersion!: number;

    [key: string]: any;

    constructor(data?: ITransitionCropCycleRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.expectedVersion = _data["expectedVersion"];
        }
    }

    static fromJS(data: any): TransitionCropCycleRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TransitionCropCycleRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["expectedVersion"] = this.expectedVersion;
        return data;
    }
}

export interface ITransitionCropCycleRequest {
    expectedVersion: number;

    [key: string]: any;
}

export class UserInfoResponse implements IUserInfoResponse {
    email!: string;
    isEmailConfirmed!: boolean;

    [key: string]: any;

    constructor(data?: IUserInfoResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.email = _data["email"];
            this.isEmailConfirmed = _data["isEmailConfirmed"];
        }
    }

    static fromJS(data: any): UserInfoResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UserInfoResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["email"] = this.email;
        data["isEmailConfirmed"] = this.isEmailConfirmed;
        return data;
    }
}

export interface IUserInfoResponse {
    email: string;
    isEmailConfirmed: boolean;

    [key: string]: any;
}

export class ValidationProblemDetails implements IValidationProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    errors?: { [key: string]: string[]; };

    [key: string]: any;

    constructor(data?: IValidationProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
            if (_data["errors"]) {
                this.errors = {} as any;
                for (let key in _data["errors"]) {
                    if (_data["errors"].hasOwnProperty(key))
                        (this.errors as any)![key] = _data["errors"][key] !== undefined ? _data["errors"][key] : [];
                }
            }
        }
    }

    static fromJS(data: any): ValidationProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ValidationProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        if (this.errors) {
            data["errors"] = {};
            for (let key in this.errors) {
                if (this.errors.hasOwnProperty(key))
                    (data["errors"] as any)[key] = (this.errors as any)[key];
            }
        }
        return data;
    }
}

export interface IValidationProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;
    errors?: { [key: string]: string[]; };

    [key: string]: any;
}

function formatDate(d: Date) {
    return d.getFullYear() + '-' +
        (d.getMonth() < 9 ? ('0' + (d.getMonth()+1)) : (d.getMonth()+1)) + '-' +
        (d.getDate() < 10 ? ('0' + d.getDate()) : d.getDate());
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}
